language: java
script:
  # Test and build app
  - mvn clean verify --file ./simple-api/pom.xml

  # Connexion Ã  docker
  - echo "$dockerPassword" | docker login -u "$dockerUserName" --password-stdin

  # Build
  - docker build -t $dockerUserName/tp-devops simple-api

  # Publication des images
  - docker push $dockerUserName/tp-devops

  # Sonarcloud
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=elenaortega_correction-tp1 --file ./simple-api/pom.xml

addons:
  sonarcloud:
    oganization: "elenaortega"
    token:
      secure: "$elenatoken"

on:
  branch: develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker
